In [1]:
!nvidia-smi

Wed Jun 10 02:36:06 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [0]:
# 安装BERT在内的Transformer软件包

In [3]:
!pip install pytorch-transformers

     |████████████████████████████████| 184kB 2.8MB/s 
     |████████████████████████████████| 1.1MB 8.8MB/s 
     |████████████████████████████████| 890kB 10.4MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=eb339c40511530c6a1c21ebcd0d99b04bbe8dd756f969c7e902d98235e625836
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [0]:
import torch
from pytorch_transformers import *

In [0]:
# 使用BERT-base模型，不区分大小写

In [7]:
config = BertConfig.from_pretrained('bert-base-uncased')

100%|██████████| 433/433 [00:00<00:00, 139124.68B/s]


In [0]:
# BERT使用的分词工具

In [9]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

100%|██████████| 231508/231508 [00:00<00:00, 419197.36B/s]


In [0]:
# 载入为区间答案型阅读理解任务预设的模型，包含前向网络输出层

In [0]:
model = BertForQuestionAnswering(config=config)

In [0]:
# 处理训练数据

In [0]:
# 获得文本分词后的单词编号，维度为batch_size*seq_length

In [0]:
input_ids = torch.tensor(tokenizer.encode('This is an example')).unsqueeze(0)

In [0]:
# 标准答案在文本中的起始位置和终止位置，维度为batch_size

In [18]:
start_positions = torch.tensor([1]); start_positions

tensor([1])

In [19]:
end_positions = torch.tensor([3]); end_positions

tensor([3])

In [0]:
# 获得模型的输出结果

In [0]:
outputs = model(input_ids, start_positions=start_positions, end_positions=end_positions)

In [22]:
outputs

(tensor(1.5323, grad_fn=<DivBackward0>),
 tensor([[-0.0160, -0.2167,  0.2935,  0.3097]], grad_fn=<SqueezeBackward1>),
 tensor([[-0.4906,  0.1133, -0.4371, -0.1771]], grad_fn=<SqueezeBackward1>))

In [0]:
# 得到交叉熵损失函数值loss，以及模型预测答案在每个位置开始和结束的打分start_scores与end_scores，维度均为batch_size*seq_length

In [0]:
loss, start_scores, end_scores = outputs

In [30]:
print('Loss：{loss}'.format(loss=loss))
print('Loss：{start_scores}'.format(start_scores=start_scores))
print('Loss：{end_scores}'.format(end_scores=end_scores))

Loss：1.532271385192871
Loss：tensor([[-0.0160, -0.2167,  0.2935,  0.3097]], grad_fn=<SqueezeBackward1>)
Loss：tensor([[-0.4906,  0.1133, -0.4371, -0.1771]], grad_fn=<SqueezeBackward1>)
