In [5]:
!nvidia-smi

Sat Jun  6 15:26:29 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [3]:
%cd ./drive/My Drive/PyTorch

/content/drive/My Drive/PyTorch


In [0]:
# !git clone https://github.com/salesforce/cove.git

In [5]:
!ls

cove  CoveTest.ipynb


In [6]:
%cd ./cove

/content/drive/My Drive/PyTorch/cove


In [7]:
!ls

cove	    get_data.sh  OpenNMT-py  requirements.txt  test
Dockerfile  LICENSE	 README.md   setup.py	       wmt_clean.py


In [0]:
# 安装所需软件包

In [8]:
!pip install -r ./requirements.txt

  Cloning git://github.com/jekbradbury/revtok.git to /tmp/pip-req-build-10vfyxwn
  Running command git clone -q git://github.com/jekbradbury/revtok.git /tmp/pip-req-build-10vfyxwn
  Cloning https://github.com/pytorch/text.git to /tmp/pip-req-build-dyzkfool
  Running command git clone -q https://github.com/pytorch/text.git /tmp/pip-req-build-dyzkfool
  Running command git submodule update --init --recursive -q
     |████████████████████████████████| 890kB 2.8MB/s 
     |████████████████████████████████| 6.4MB 12.5MB/s 
     |████████████████████████████████| 71kB 8.6MB/s 
     |████████████████████████████████| 1.1MB 48.1MB/s 
     |████████████████████████████████| 51kB 6.6MB/s 
     |████████████████████████████████| 61kB 7.6MB/s 
     |████████████████████████████████| 235kB 41.6MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=e48f57def1945f03da9a599f0eca800e346f5ee2a786e43ce01512a27b1fe80a
  Stored in directory: /root/.cache/pip/w

In [0]:
# 安装CoVe

In [10]:
!python setup.py develop

running develop
running egg_info
creating cove.egg-info
writing cove.egg-info/PKG-INFO
writing dependency_links to cove.egg-info/dependency_links.txt
writing top-level names to cove.egg-info/top_level.txt
writing manifest file 'cove.egg-info/SOURCES.txt'
writing manifest file 'cove.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.6/dist-packages/cove.egg-link (link to .)
Adding cove 1.0.0 to easy-install.pth file

Installed /content/drive/My Drive/PyTorch/cove
Processing dependencies for cove==1.0.0
Finished processing dependencies for cove==1.0.0


In [0]:
import torch
from torchtext.vocab import GloVe
from cove import MTLSTM

In [0]:
# GloVe词表，维度为2.1*10^6*3

In [13]:
glove = GloVe(name='840B', dim=300, cache='.embeddings')

.embeddings/glove.840B.300d.zip: 2.18GB [16:54, 2.15MB/s]                            
100%|█████████▉| 2195422/2196017 [05:44<00:00, 8903.84it/s]

In [0]:
# 输入2个句子，每个句子中每个单词在词表中的编号

In [15]:
inputs = torch.LongTensor([[10, 2, 3, 0], [7, 8, 10, 3]]);inputs

tensor([[10,  2,  3,  0],
        [ 7,  8, 10,  3]])

In [0]:
# 两个句子的长度分别为3和4

In [17]:
lengths = torch.LongTensor([3, 4]);lengths

tensor([3, 4])

In [0]:
# CoVe类

In [19]:
cove = MTLSTM(n_vocab=glove.vectors.shape[0], vectors=glove.vectors, model_cache='.embeddings')

Downloading: "https://s3.amazonaws.com/research.metamind.io/cove/wmtlstm-8f474287.pth" to .embeddings/wmtlstm-8f474287.pth


In [0]:
# 每个句子每个单词的CoVe编码，维度为2*4*600

In [21]:
outputs = cove(inputs, lengths);outputs

tensor([[[ 0.0022, -0.0025, -0.0006,  ..., -0.0115,  0.0006,  0.0053],
         [ 0.0029,  0.0088, -0.0009,  ..., -0.0060, -0.0003,  0.0017],
         [ 0.0056, -0.1044, -0.0194,  ...,  0.0117,  0.0059,  0.0033],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.0080,  0.0234,  0.0019,  ...,  0.0128,  0.0041,  0.0154],
         [ 0.0105, -0.0049,  0.0007,  ...,  0.0111, -0.0014,  0.0320],
         [ 0.0103,  0.0004, -0.0003,  ..., -0.0099, -0.0003,  0.0112],
         [ 0.0151, -0.1938,  0.0019,  ...,  0.0128, -0.0014,  0.0055]]])

In [22]:
outputs.shape

torch.Size([2, 4, 600])